name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2 # 가정된 최신 버전으로 변경
        if: always()
        with:
          files: target/**/*.xml
