name: CI

# This pipeline runs when pushed to the main branch and branches starting with feature/
on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out steps
    - uses: actions/checkout@v2

    # Java 8 setting steps
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    # Steps to build an application using Maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    # Steps to post unit test results
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: target/**/*.xml

    # Build artifact upload steps
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: my-app-1.0
        path: target/*

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Check out steps
    - uses: actions/checkout@v2

    # Docker setting steps
    - name: Install Docker
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    # Docker image build steps
    - name: Docker build
      run: |
        docker build -t my-app:1.0 .

    # Docker 이미지를 GitHub Container Registry에 푸시하는 스텝 (선택적)
    # - name: Push to GitHub Container Registry
    #   run: |
    #     echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    #     docker push ghcr.io/your-username/my-app:1.0

